In [12]:
# Useful additional packages
import matplotlib.pyplot as plt
import numpy as np
from math import pi
from qiskit import QuantumCircuit
from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister, transpile
from qiskit.tools.visualization import circuit_drawer
from qiskit.quantum_info import state_fidelity

In [13]:
# Create a Quantum Circuit acting on a quantum register of three qubits
circ = QuantumCircuit(2)
q = QuantumRegister(1)

In [14]:
 
 	
 
 	
   
qc = QuantumCircuit(q)
qc.u(pi/2,pi/4,pi/8,q)
qc.draw()



┌────────────────┐
q1: ┤ U(π/2,π/4,π/8) ├
    └────────────────┘

In [38]:
from qiskit.quantum_info import Pauli, Operator

# Define the Pauli matrices
sigma_x = Pauli('X')
sigma_y = Pauli('Y')
sigma_z = Pauli('Z')

# # Define the two basis states |a'> and |a''>
# a_prime = Operator.from_label('0')  # |a'> = |0>
# a_double_prime = Operator.from_label('1')  # |a''> = |1>
# Define the two basis states |a'> and |a''> as 2x1 column vectors
a_prime = Operator(np.array([[1], [0]]))  # |a'> = |0>
a_double_prime = Operator(np.array([[0], [1]]))  # |a''> = |1>



delta = 1
# Create the Hamiltonian term |a'><a''|
hamiltonian_term = delta * (a_prime.tensor(a_double_prime.adjoint()) + a_double_prime.tensor(a_prime.adjoint()))

# You can now work with this Hamiltonian term, for example, apply it to a quantum state or perform operations.


In [39]:
# import numpy as np
from qiskit.quantum_info import Operator

# Define your quantum state as a numpy array
psi = np.array([1 / np.sqrt(2), 1 / np.sqrt(2)])  # For example, |0> + |1>

# Define your Hamiltonian operator
H = Operator(hamiltonian_term)  # Replace 'your_hamiltonian_matrix' with the actual matrix

# Apply the Hamiltonian to the quantum state
result_state = H.data.dot(psi)

# 'result_state' now contains the quantum state after applying the Hamiltonian


In [40]:
# result_state  # This shows the result of applying the Hamiltonian to the quantum state, when superposed with |0> + |1>

array([0.70710678+0.j, 0.70710678+0.j])

In [49]:
# Now we try to simulate the time evolution of the system when the state is |a'> = |0>
psi_a_prime = np.array([1, 0])  # |a'> = |0>
psi_a_double_prime = np.array([0, 1])  # |a''> = |1>

# Define the time variable
t = 0.0001

# Define the time evolution operator
U = Operator(np.cos(t) * np.eye(2) - 1j * np.sin(t) * hamiltonian_term)

# Apply the time evolution operator to the initial state
result_state = U.data.dot(psi_a_prime)

# 'result_state' now contains the quantum state after applying the time evolution operator to the initial state






In [50]:
result_state

array([1.+0.00000000e+00j, 0.-9.99999998e-05j])

In [46]:
H.data.dot(psi_a_prime)

array([0.+0.j, 1.+0.j])

In [24]:
import qiskit.tools.jupyter
%qiskit_version_table
%qiskit_copyright